[package]
name = "himalaya"
description = "CLI to manage emails."
version = "0.9.0"
authors = ["soywod <clement.douin@posteo.net>"]
edition = "2021"
license = "MIT"
categories = ["command-line-interface", "command-line-utilities", "email"]
keywords = ["cli", "mail", "email", "client", "imap"]
homepage = "https://pimalaya.org/himalaya"
documentation = "https://pimalaya.org/himalaya/"
repository = "https://github.com/soywod/himalaya/"
metadata.docs.rs.all-features = true

[features]
default = [
  "imap-backend",
  # "notmuch-backend",
  "smtp-sender",
  # "pgp-commands",
  # "pgp-gpg",
  # "pgp-native",
]
imap-backend = ["email-lib/imap-backend"]
notmuch-backend = ["email-lib/notmuch-backend"]
smtp-sender = ["email-lib/smtp-sender"]
pgp = []
pgp-commands = ["pgp", "email-lib/pgp-commands"]
pgp-gpg = ["pgp", "email-lib/pgp-gpg"]
pgp-native = ["pgp", "email-lib/pgp-native"]

# dev dependencies
[dev-dependencies]
async-trait = "0.1"

tempfile = "3.3"

[dependencies]

anyhow = "1.0"
chrono = "0.4.24"
clap = "4.0"
clap_complete = "4.0"
clap_mangen = "0.2"
console = "0.15.2"
dialoguer = "0.10.2"
dirs = "4.0.0"
email_address = "0.2.4"
env_logger = "0.8"
erased-serde = "0.3"
indicatif = "0.17"
log = "0.4"
md5 = "0.7.0"
mml-lib = { version = "=0.5.0", default-features = false }
once_cell = "1.16.0"
email-lib = { version = "=0.15.3", default-features = false }
keyring-lib = "=0.1.0"
oauth-lib = "=0.1.0"
process-lib = "=0.1.0"
secret-lib = "=0.1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
shellexpand-utils = "=0.1.0"
termcolor = "1.1"
terminal_size = "0.1"
tokio = { version = "1.23", default-features = false, features = [
  "macros",
  "rt-multi-thread",
] }
toml = "0.7.4"
toml_edit = "0.19.8"
unicode-width = "0.1"
url = "2.2"
uuid = { version = "0.8", features = ["v4"] }

[target.'cfg(target_env = "musl")'.dependencies.rusqlite]
version = "0.29"
features = []

[target.'cfg(not(target_env = "musl"))'.dependencies.rusqlite]
version = "0.29"
features = ["bundled"]

[target.'cfg(not(windows))'.dependencies.coredump]
version = "=0.1.2"
